export {
  getProfile,
  getExperience,
  getProjects,
  getFeaturedProjects,
  getProjectBySlug,
  getCertifications,
  getSkills,
  getVolunteering,
  getHonors,
  getTestimonials,
  getFaq,
  buildFaqLd,
  getTimeline,
} from "./data";
